### ISSUE TITLE
Redmine 3.x compatibility ?

### ISSUE THREAD

**Issue by LeDistordu** [gs-lab/redmine_daily_status#29]
This plugin is Redmine 3.x compatibility ?

**Comment by LeDistordu** [comment]
I have a 

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.


When i click on "Daily Status" in project.

In my Nginx log : 

2015/04/17 11:00:31 [info] 15198#0: *740013 recv() failed (104: Connection reset by peer) while sending to client, client: 172.16.3.2, server: localhost, request: "HEAD / HTTP/1.0", upstream: "passenger:unix:/tmp/passenger.bvIniIP/agents.s/server"

Nothing in my Redmine Log.

**Comment by romankalb** [comment]
This is what I get 

>Started GET "/projects/plugin-development/daily_status" for ::1 at 2015-07-10 08:25:39 +0300
>Processing by DailyStatusesController#index as HTML
>  Parameters: {"project_id"=>"plugin-development"}
>  Current user: admin (id=1)
>Completed 500 Internal Server Error in 17ms (ActiveRecord: 0.0ms)

>NoMethodError (undefined method `todays_status_for' for #<Class:0x0000000c07be60>):
>  activerecord (4.2.1) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
>  plugins/redmine_daily_status/app/models/daily_status_project_patch.rb:11:in `todays_status'
>  plugins/redmine_daily_status/app/controllers/daily_statuses_controller.rb:9:in `index'
>  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
>  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
>  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
>  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
>  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
>  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
>  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
>  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
>  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
>  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
>  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
>  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
>  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
>  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
>  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
>  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
>  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
>  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
>  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
>  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
>  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
>  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
>  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
>  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
>  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
>  rack (1.6.4) lib/rack/etag.rb:24:in `call'
>  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
>  rack (1.6.4) lib/rack/head.rb:13:in `call'
>  actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
>  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
>  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
>  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
>  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
>  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
>  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
>  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
>  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
>  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
>  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
>  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
>  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
>  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
>  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
>  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
>  railties (4.2.1) lib/rails/engine.rb:518:in `call'
>  railties (4.2.1) lib/rails/application.rb:164:in `call'
>  rack (1.6.4) lib/rack/lock.rb:17:in `call'
>  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
>  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
>  c:/Ruby/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
>  c:/Ruby/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
>  c:/Ruby/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

My redmine config 
![image](https://cloud.githubusercontent.com/assets/8047387/8612735/017f8b1c-26de-11e5-8ac8-5702f728bb0c.png)

**Comment by soncu** [comment]
Similar problem here:
```
Started GET "/projects/12/daily_status" for  at 2015-11-09 08:22:52 +0200
Processing by DailyStatusesController#index as HTML
  Parameters: {"project_id"=>"12"}
  Current user: x (id=80)
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.9ms)

NoMethodError (undefined method `todays_status_for' for #<Class:0x00000003638eb0>):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by leaver** [comment]
Did you resolved it now? @soncu @romankalb @LeDistordu

**Comment by soncu** [comment]
no
